### ISSUE TITLE
Delay in receiving data from TACACS+ server while authenticating

### ISSUE THREAD

**Issue by sreejithcj** [martinclaro/tacacs-php#3]
In Client.php, sock_recv waits for around 3 minutes before successfully receiving data from TACACS+ server and authenticates the user. 

This is in CentOS with PHP 5.4. Socket timeout in php.ini is 60 seconds.

**Comment by martinclaro** [comment]
@sreejithcj Please check latest commit at master (24e1d0c39e8697697409690d83f4444bbb56cb0b) and let me know if that commit solves the issue. I think this issue is related to #4.

**Comment by sreejithcj** [comment]
I had to introduce @socket_set_option($this->socket, SOL_SOCKET, SO_RCVTIMEO, array("sec" => 1, "usec" => 0)); before socket_recv in Client.php to avoid the waiting period. Interestingly, there is no delay when running the same application in Windows machine.

**Comment by martinclaro** [comment]
Added RECVTIMEO and SENDTIMEO socket settings.
Commited in 45b3317fad236edcd9345327c16f04f03817f466
