### ISSUE TITLE
Status field of received packet is 0 intermittently

### ISSUE THREAD

**Issue by sreejithcj** [martinclaro/tacacs-php#4]
In parseBinary in Packet.php, $binHeader gets 13 bytes intermittently instead of 12. Due to this, the status field has the value 0. Due to this, the control goes to the else part (Continue packet) in Client.php authenticate function. But in TACACS server, user is successfully authenticated.

**Comment by martinclaro** [comment]
Fixed a bug at getPseudoPad() method at Common/Packet/Header.php in master. A bug in pseudo_pad generator algorithm was causing a non-compliant pseudo_pad value.

Please try the latest revision from master and let me know if this bugfix solves this issue. No need to change other methods.

**Comment by sreejithcj** [comment]
I fixed issue #5 by doing strlen(bin2hex($data) in "send" in Client.php and was getting the response back from the server. But, when we parse the response in parseBinary in Packet.php, $binHeader is 13  at times instead of 12.

**Comment by martinclaro** [comment]
@sreejithcj I've tried many different user/pass/secret alternatives and I couldn't reproduce this issue after commit 24e1d0c39e8697697409690d83f4444bbb56cb0b. Please provide a test set of credentials (username/password/secret) in order to let us reproduce the issue you mentioned.

BTW, as substr() function allows to split a binary stream safely, you couldn't get 13 bytes after calling:
```
$binHeader = substr($binaryData, 0, TAC_PLUS_HDR_SIZE);
```

**Comment by sreejithcj** [comment]
Its not working for me still. I am trying to get more details. Will come back with more details. Thanks.

**Comment by sreejithcj** [comment]
I have found the reason for this issue. In my php.ini file (PHP 5.4.24 on CentOS), mbstring is enabled with the following entries. When I comment all 4 lines related to mbstring the issues #5 and #4 are resolved.

[mbstring]
mbstring.internal_encoding=UTF-8
mbstring.http_output=UTF-8
mbstring.func_overload=6

To help you debug this further, when mbstring entries are present in php.ini file, most of the time I get it right in Packet.php parseBinary function like below:

$binaryData = c101020000007678000000061e33bcfdf528
$binHeader =  c10102000000767800000006
				     
But at times it will not be correct.

$binaryData = c1010200000035ed00000006d505df836602
$binHeader =  c1010200000035ed00000006d505df83

You can see that here, the substr() returns a wrong header.

Hope this helps.

**Comment by sreejithcj** [comment]
Also:

1. Username/Password I am using is priv15/priv15. But this issue can be reproduced with any username/password combination. 
2. I guess other features are using mbstring, so not sure I can comment them in my php.ini
3. Found a discussion on this subject at: http://stackoverflow.com/questions/4570812/byte-manipulation-in-php

**Comment by martinclaro** [comment]
Actually,  the issue is related to mbstring_overload (http://php.net/manual/en/mbstring.overload.php). 

I'll analyze a different approach to avoid those configurations to break getPseudoPad and other methods.

**Comment by sreejithcj** [comment]
Thanks Martin. Will wait :)

**Comment by martinclaro** [comment]
@sreejithcj Please update your copy to the latest master commit (b5a1cc822a402b01ad3762b6cd9d3bb4a9f8f38c) and check if it's working now.

**Comment by sreejithcj** [comment]
Hi Martin,

Thank you for the quick response and fixes. These commits have fixed the issues #4 and #5.
I could manage #3 by introducing a socket timeout with @socket_set_option before @socket_recv
