### ISSUE TITLE
Wrong data length posted to TACACS+ server in Socket send

### ISSUE THREAD

**Issue by sreejithcj** [martinclaro/tacacs-php#5]
In Client.php function send(), strlen($data) was returning 28 bytes while I was actually writing 30 bytes to TACACS+ server. I then used strlen(bin2hex($data) to get the length right.

**Comment by martinclaro** [comment]
@sreejithcj Please check latest commit at master (24e1d0c39e8697697409690d83f4444bbb56cb0b) and let me know if that commit solves the issue. I think this issue is related to #4.

**Comment by sreejithcj** [comment]
More details:

Client Machine: CentOs with PHP Ver. 5.4
Server: Cisco ACS 4.0 at Port 49

Try to authenticate with a user account present in server. When I do a Packet capture in server, it shows a Malformed packet Please see the screenshot below from Wireshark.

![image](https://cloud.githubusercontent.com/assets/1614294/10343615/36a3c12e-6d3c-11e5-8030-ec68deda0faa.png)


I am writing 30 bytes (Header-12 + Body-18) but the strlen in send($packet) in Client.php is only 28.

**Comment by martinclaro** [comment]
Fixed in b5a1cc822a402b01ad3762b6cd9d3bb4a9f8f38c
